<a href="https://colab.research.google.com/github/DarshanDinni/learn_pytorch/blob/main/0_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pytorch Fundamentals

In [2]:
# Importing the libraries
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Checking the version of pytorch
print(torch.__version__)

2.1.0+cu118


##Fundamentals of Tensors

In [4]:
# Creating scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [5]:
# Checking the dimension of the tensor
scalar.ndim

0

In [6]:
# Checking the shape of the tensor
scalar.shape

torch.Size([])

In [7]:
# Creating vector
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [8]:
# Checking the dimension of the tensor
vector.ndim

1

In [9]:
# Checking the shape of the tensor
vector.shape

torch.Size([2])

In [10]:
# Creating tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
# Checking the dimension of the tensor
TENSOR.ndim

3

In [12]:
# Checking the shape of the tensor
TENSOR.shape

torch.Size([1, 3, 3])

##Creating Random values

We use random values because neural network starts intitally with random values and then updates them to train itself.

In [14]:
# Creating the random values using torch
custom_random_values = torch.rand(1,2,3)
custom_random_values

tensor([[[0.1949, 0.3092, 0.6109],
         [0.0064, 0.5626, 0.1177]]])

In [15]:
# Creating the random values for an color image of (255,255) dimensions
custom_image_values = torch.rand(255, 255, 3)             # 3 indicates the color channels (R, G, B)
custom_image_values.ndim, custom_image_values.shape

(3, torch.Size([255, 255, 3]))

##Zero and One tensors

In [17]:
# Creating the zero tensor
zero_tensor = torch.zeros(2,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zero_tensor.dtype

torch.float32

In [18]:
# Creating the one tensor
one_tensor = torch.ones(2,4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
# Creating range of values
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [21]:
# Creating the zero tensor with same shape as one_to_ten tensor
zero_tensor_like = torch.zeros_like(input=one_to_ten)
zero_tensor_like

tensor([0, 0, 0, 0, 0])

##Tensor datatypes

In [25]:
# Creating the tensor of float32 datatype
float32_tensor = torch.tensor([1.0, 2.0, 3.0],
                              dtype=None,    # We can set the data type of the tensor (default is float32)
                              device=None,   # We can set the value of device to 'cpu' and 'cuda'
                              requires_grad=False    # We can set this to 'True' or 'False' to track the gradient of tensors
                              )
float32_tensor

tensor([1., 2., 3.])

In [26]:
# Checking the datatype of the tensors
float32_tensor.dtype

torch.float32

In [28]:
# Converting the float32_tensor to float16 tensor
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [29]:
# Checking the data type
float16_tensor.dtype

torch.float16

##Tensor manipulation
**Tensor Operations:**

1. Add
2. Substract
3. Multiply
4. Divide
5. Matrix multiplication


In [30]:
# dummy_tensor_1 =

SyntaxError: ignored