<a href="https://colab.research.google.com/github/DarshanDinni/learn_pytorch/blob/main/0_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pytorch Fundamentals

In [2]:
# Importing the libraries
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Checking the version of pytorch
print(torch.__version__)

2.1.0+cu118


##Fundamentals of Tensors

In [4]:
# Creating scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [5]:
# Checking the dimension of the tensor
scalar.ndim

0

In [6]:
# Checking the shape of the tensor
scalar.shape

torch.Size([])

In [7]:
# Creating vector
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [8]:
# Checking the dimension of the tensor
vector.ndim

1

In [9]:
# Checking the shape of the tensor
vector.shape

torch.Size([2])

In [10]:
# Creating tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
# Checking the dimension of the tensor
TENSOR.ndim

3

In [12]:
# Checking the shape of the tensor
TENSOR.shape

torch.Size([1, 3, 3])

##Creating Random values

We use random values because neural network starts intitally with random values and then updates them to train itself.

In [13]:
# Creating the random values using torch
custom_random_values = torch.rand(1,2,3)
custom_random_values

tensor([[[0.0920, 0.6285, 0.8391],
         [0.7434, 0.9068, 0.2249]]])

In [14]:
# Creating the random values for an color image of (255,255) dimensions
custom_image_values = torch.rand(255, 255, 3)             # 3 indicates the color channels (R, G, B)
custom_image_values.ndim, custom_image_values.shape

(3, torch.Size([255, 255, 3]))

##Zero and One tensors

In [15]:
# Creating the zero tensor
zero_tensor = torch.zeros(2,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
zero_tensor.dtype

torch.float32

In [17]:
# Creating the one tensor
one_tensor = torch.ones(2,4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
# Creating range of values
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [19]:
# Creating the zero tensor with same shape as one_to_ten tensor
zero_tensor_like = torch.zeros_like(input=one_to_ten)
zero_tensor_like

tensor([0, 0, 0, 0, 0])

##Tensor datatypes

In [20]:
# Creating the tensor of float32 datatype
float32_tensor = torch.tensor([1.0, 2.0, 3.0],
                              dtype=None,    # We can set the data type of the tensor (default is float32)
                              device=None,   # We can set the value of device to 'cpu' and 'cuda'
                              requires_grad=False    # We can set this to 'True' or 'False' to track the gradient of tensors
                              )
float32_tensor

tensor([1., 2., 3.])

In [21]:
# Checking the datatype of the tensors
float32_tensor.dtype

torch.float32

In [22]:
# Converting the float32_tensor to float16 tensor
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [23]:
# Checking the data type
float16_tensor.dtype

torch.float16

##Tensor manipulation
**Tensor Operations:**

1. Add
2. Substract
3. Multiply
4. Divide
5. Matrix multiplication


In [24]:
dummy_tensor_1 = torch.rand(2,3)
dummy_tensor_1

tensor([[0.7199, 0.7369, 0.8332],
        [0.0831, 0.2294, 0.4343]])

In [25]:
# Addition of tensor - 1st Way
add_op_dummy_tensor_1 = dummy_tensor_1 + 10
add_op_dummy_tensor_1

tensor([[10.7199, 10.7369, 10.8332],
        [10.0831, 10.2294, 10.4343]])

In [26]:
# Addition of tensor - 2nd Way
add_op_dummy_tensor_1 = torch.add(dummy_tensor_1, 10)
add_op_dummy_tensor_1

tensor([[10.7199, 10.7369, 10.8332],
        [10.0831, 10.2294, 10.4343]])

Same applies for sub, multiply, divide we can use

**torch.mul,torch.subtract, torch.divide**

In [27]:
# Matrix multiplication if tensors
tensor_A = torch.tensor([[2, 3],
                         [4, 5],
                         [6, 7]])

tensor_B = torch.tensor([[6, 7],
                         [4, 5],
                         [2, 3]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

As the above error is common because of the shape issues of tensor A and tensor B.

So to fix this we can use transpose function to change the shape of matrix.

In [28]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[33, 23, 13],
        [59, 41, 23],
        [85, 59, 33]])

##Tensor aggregation

Finding the minimum, maximum, average etc from the tensor

In [29]:
# Finding the mean of tensor_A

torch.mean(tensor_A)

RuntimeError: ignored

In [33]:
# To solve the error above we need to convert the tensor_A to long type
print(tensor_A)
torch.mean(tensor_A.type(torch.float32))

tensor([[2, 3],
        [4, 5],
        [6, 7]])


tensor(4.5000)

## Reshape, View, Stacking, Squeeze, Unsqueeze, Permute to a tensor

Reshape - it reshapes the input tensor to defined shape

View - it returns the view of the tensor but it shares the same memory as the original tensor

Stacking - combine tensors on top of each other

Squeeze - remove 1 dimension from the tensor

Unsqueeze - adds 1 dimension to the tensor

Permute - return a view of the tensor with permited dimensions(swapped dimensions)

In [35]:
# Reshape - it reshapes the input tensor to defined shape
tensor_1 = torch.arange(1.0, 20, 2)
tensor_1, tensor_1.shape

(tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.]), torch.Size([10]))

In [37]:
#  reshaping the tensor_1
reshaped_tensor_1 = tensor_1.reshape(2, 5)
reshaped_tensor_1

tensor([[ 1.,  3.,  5.,  7.,  9.],
        [11., 13., 15., 17., 19.]])

In [38]:
# View - it returns the view of the tensor but it shares the same memory as the
# original tensor

# As the results is same as the reshape but viewed tensor has the same memory i.e any changes
# made to viewed_tensor_1 makes the same changes with the tensor_1

viewed_tensor_1 = tensor_1.view(2,5)
viewed_tensor_1

tensor([[ 1.,  3.,  5.,  7.,  9.],
        [11., 13., 15., 17., 19.]])